'use client'

import { useState, useEffect } from 'react'
import { FileText, FileSpreadsheet, FileCode, Download, ExternalLink, Image as ImageIcon, Loader2, Sparkles } from 'lucide-react'
import { MessageAttachment } from '@/lib/store/dummyData'
import { getAttachmentSignedUrl } from '@/lib/attachments/upload'
import { formatFileSize } from '@/lib/attachments/validation'

export function AttachmentBubbleItem({ attachment }: { attachment: MessageAttachment }) {
  const [signedUrl, setSignedUrl] = useState<string | null>(attachment.signedUrl || null)
  const [isLoadingUrl, setIsLoadingUrl] = useState(!attachment.signedUrl)
  const isImage = attachment.attachment_type === 'image'
  const isGenerated = (attachment.metadata as Record<string, unknown>)?.source === 'generated_image'

  // Fetch temporary signed URL on mount if not already populated
  // Flow: message_attachments -> storage_path -> getAttachmentSignedUrl() -> render attachment
  useEffect(() => {
    let isMounted = true

    if (!signedUrl && attachment.storage_path) {
      setIsLoadingUrl(true)
      getAttachmentSignedUrl(attachment.storage_path)
        .then((url) => {
          if (isMounted) {
            setSignedUrl(url)
            setIsLoadingUrl(false)
          }
        })
        .catch(() => {
          if (isMounted) {
            setIsLoadingUrl(false)
          }
        })
    }

    return () => {
      isMounted = false
    }
  }, [attachment.storage_path, signedUrl])

  const getDocIcon = (filename: string) => {
    const ext = filename.split('.').pop()?.toLowerCase() || ''
    if (ext === 'csv') return <FileSpreadsheet size={16} className="text-emerald-500" />
    if (['json', 'md'].includes(ext)) return <FileCode size={16} className="text-amber-500" />
    return <FileText size={16} className="text-blue-500" />
  }

  // 1. Image Attachment Rendering
  if (isImage) {
    return (
      <div className={`overflow-hidden rounded-2xl border border-zinc-200/80 bg-zinc-100/60 dark:border-zinc-800 dark:bg-zinc-900/60 shadow-xs ${
        isGenerated ? 'max-w-[340px] sm:max-w-[460px]' : 'max-w-[280px] sm:max-w-[340px]'
      }`}>
        {isLoadingUrl ? (
          <div className="flex h-44 w-full items-center justify-center bg-zinc-100 dark:bg-zinc-800 text-zinc-400">
            <Loader2 size={20} className="animate-spin text-zinc-500" />
          </div>
        ) : signedUrl ? (
          <a
            href={signedUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="group block relative cursor-pointer overflow-hidden"
            title="Click to view full image"
          >
            {isGenerated && (
              <div className="absolute top-2.5 left-2.5 z-10 flex items-center gap-1.5 rounded-full bg-black/60 px-2.5 py-1 text-[10.5px] font-medium text-white shadow-sm backdrop-blur-md">
                <Sparkles size={11} className="text-amber-400" />
                <span>Generated by AI</span>
              </div>
            )}
            <img
              src={signedUrl}
              alt={attachment.file_name}
              className={`w-full transition-transform duration-200 group-hover:scale-101 ${
                isGenerated 
                  ? 'max-h-[480px] object-contain bg-black/5 dark:bg-black/30' 
                  : 'max-h-64 object-cover'
              }`}
            />
            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center opacity-0 group-hover:opacity-100">
              <span className="rounded-full bg-black/60 px-2.5 py-1 text-[11px] font-medium text-white flex items-center gap-1 backdrop-blur-xs">
                <ExternalLink size={12} />
                <span>Open full</span>
              </span>
            </div>
          </a>
        ) : (
          <div className="flex h-28 w-full items-center justify-center bg-zinc-100 dark:bg-zinc-800 text-xs text-zinc-400">
            Image unavailable
          </div>
        )}

        <div className="flex items-center justify-between p-2.5 text-xs">
          <div className="min-w-0 pr-2">
            <p className="truncate font-medium text-zinc-800 dark:text-zinc-200 text-[11.5px]">
              {attachment.file_name}
            </p>
            <p className="text-[10px] text-zinc-400">
              {formatFileSize(attachment.file_size)}
              {isGenerated && ' • FLUX'}
            </p>
          </div>
          {signedUrl && (
            <a
              href={signedUrl}
              download={attachment.file_name}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-lg p-1.5 text-zinc-400 hover:bg-zinc-200 hover:text-zinc-700 dark:hover:bg-zinc-800 dark:hover:text-zinc-200 transition-colors"
              title="Download image"
            >
              <Download size={13} />
            </a>
          )}
        </div>
      </div>
    )
  }

  // 2. Document Attachment Rendering
  return (
    <div className="flex items-center justify-between gap-3 rounded-2xl border border-zinc-200/90 bg-zinc-50/80 p-2.5 px-3 text-xs shadow-xs dark:border-zinc-800 dark:bg-zinc-900/80 min-w-[200px] max-w-[280px] sm:max-w-[320px]">
      <div className="flex items-center gap-2.5 min-w-0">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-zinc-200/60 dark:bg-zinc-800">
          {getDocIcon(attachment.file_name)}
        </div>
        <div className="min-w-0">
          <p className="truncate font-medium text-zinc-900 dark:text-zinc-100 text-xs">
            {attachment.file_name}
          </p>
          <p className="text-[10px] text-zinc-400">
            {formatFileSize(attachment.file_size)}
          </p>
        </div>
      </div>

      <div>
        {isLoadingUrl ? (
          <Loader2 size={14} className="animate-spin text-zinc-400" />
        ) : signedUrl ? (
          <a
            href={signedUrl}
            download={attachment.file_name}
            target="_blank"
            rel="noopener noreferrer"
            className="flex h-7 w-7 items-center justify-center rounded-lg bg-zinc-200/60 hover:bg-zinc-200 text-zinc-700 dark:bg-zinc-800 dark:hover:bg-zinc-700 dark:text-zinc-200 transition-colors cursor-pointer"
            title="Download document"
          >
            <Download size={13} />
          </a>
        ) : null}
      </div>
    </div>
  )
}
